exhibitions/urls.py
from django.conf.urls import url
from . import views


app_name = 'exhibitions'
urlpatterns = [
	url(r'^(?P<slug>[0-9A-Za-z\-_]+)/past', views.PastView.as_view(), name='past'),
    url(r'^(?P<slug>[0-9A-Za-z\-_]+)/$', views.IndexView.as_view(), name='detail'),
    # url(r'^$', views.IndexView.as_view(), name='index'),
]

exhibitions/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db.models import *
from tinymce.models import HTMLField
from base.models import Base, ContentBlock, Tool, Facilitator, Training

class Exhibition(Base):
    class Meta:
        ordering = ['start_date', 'name']

    name = CharField(max_length=200, null=True)
    slug = SlugField(max_length=200)
    start_date = DateTimeField()
    end_date = DateTimeField()
    description = HTMLField(null=True)
    content_blocks = ManyToManyField(ContentBlock, blank=True)
    tools = ManyToManyField(Tool, blank=True)
    facilitators = ManyToManyField(Facilitator, blank=True)
    trainings = ManyToManyField(Training, blank=True)
    link = URLField(null=True, blank=True)

exhibitions/views.py
from datetime import datetime, timedelta, time
from django.conf import settings
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Exhibition, ContentBlock


class IndexView(generic.TemplateView):
    template_name = 'exhibitions/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)

        exhibition = get_object_or_404(Exhibition, slug=self.kwargs['slug'])

        today = datetime.now().date()

        context['exhibition'] = exhibition
        context['trainings'] = exhibition.trainings.filter(date__gte=today)
        context['content_blocks'] = exhibition.content_blocks.all()
        context['tools'] = exhibition.tools.all()
        context['facilitators'] = exhibition.facilitators.all()
        context['site_url'] = settings.SITE_URL

        if 'slug' in self.kwargs:
            context['slug'] = self.kwargs['slug']

        return context


class PastView(generic.TemplateView):
    template_name = 'exhibitions/past.html'

    def get_context_data(self, **kwargs):
        context = super(PastView, self).get_context_data(**kwargs)

        exhibition = get_object_or_404(Exhibition, slug=self.kwargs['slug'])

        today = datetime.now().date()

        context['exhibition'] = exhibition
        context['trainings'] = exhibition.trainings.filter(date__lte=today).order_by('-date')
        context['content_blocks'] = exhibition.content_blocks.all()
        context['site_url'] = settings.SITE_URL

        return context

exhibitions/templates/exhibitions/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Wound</title>
	<meta name="description" content="" />
	<meta name="keywords" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'exhibitions/css/style.css' %}" />
</head>
<body>
    {% block navigation %}
    {% endblock navigation %}
    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>
    <script type="text/javascript" src="{% static 'base/js/min/velocity.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'base/js/min/velocity.ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'exhibitions/js/site.js' %}"></script>
</body>
</html>

exhibitions/templates/exhibitions/content-blocks.html
{% for content_block in content_blocks %}
	{% if not forloop.first %}
	<!-- {{ content_block.name|upper }} -->
	<section class="section section-{{ content_block.slug }}" id="{{ content_block.slug }}">
		<h2 class="section-header">{{ content_block.name|upper }}  <a href="#{{ content_block.slug }}"><i class="fa fa-chain fa-chain-big"></i></a></h2>
		<div class="section-content">{{ content_block.content|safe }}</div>
	</section>
	{% endif %}
{% endfor %}

exhibitions/templates/exhibitions/detail.html
<h1>{{ tool.caption }}</h1>

exhibitions/templates/exhibitions/facilitators.html
<section class="section section-facilitators" id="facilitators">
	<h2 class="section-header">FACILITATORS  <a href="#facilitators"><i class="fa fa-chain fa-chain-big"></i></a></h2>
		<div class="section-content">
			<div class="facilitators-row">
			{% for facilitator in facilitators %}
				<div class="facilitator" id="{{ facilitator.slug }}">
					<h3 class="facilitator-name">{{ facilitator.name }}  <a href="#{{ facilitator.slug }}"><i class="fa fa-chain"></i></a></h3>
					<div class="facilitator-description">{{ facilitator.description|safe }}</div>
					{% if facilitator.description|length > 300 %}
					<a href="#" class="facilitator-toggle">read more</a>
					{% endif %}
				</div>
			{% if forloop.counter|divisibleby:"2" %}
			</div>
			<div class="facilitators-row">
			{% endif %}
			{% endfor %}
		</div>
	</div>
</section>

exhibitions/templates/exhibitions/index.html
{% extends "exhibitions/base.html" %}

{% block navigation %}
{% include 'exhibitions/navigation.html' %}
{% endblock navigation %}

{% block content %}

{% include 'exhibitions/intro.html' %}

<!-- TOOLS -->
{% include 'exhibitions/tools.html' %}

<!-- TRAININGS -->
<section class="section section-trainings" id="trainings">
	<h2 class="section-header">TRAININGS  <a href="#trainings"><i class="fa fa-chain fa-chain-big"></i></a></h2>
	{% include 'exhibitions/trainings.html' %}
</section>

<!-- FACILITATORS -->
{% include 'exhibitions/facilitators.html' %}

{% include 'exhibitions/content-blocks.html' %}

{% endblock content %}

exhibitions/templates/exhibitions/intro.html
{% load static %}

<header id="header">
	<!-- INTRO -->
	<section class="section section-{{ content_blocks.first.slug }}" id="{{ content_blocks.first.slug }}">
		<div class="section-content">
			{{ content_blocks.first.content|safe }}
		</div>
		<img 
			class="header" 
			alt="Wound" 
			src="{% static 'base/images/wound_space.jpg' %}" 
			loading="lazy"
		/>
	</section>
</header>

exhibitions/templates/exhibitions/navigation.html
<nav class="navigation">
	<div class="navicon">&#9776;</div>
	<ul class="navigation-menu">
		<li class="navigation-menu-item">
			<a href="{% url 'exhibitions:detail' exhibition.slug %}#header">Wound</a>
		</li>
		<li class="navigation-menu-item">
			<a href="{% url 'exhibitions:detail' exhibition.slug %}#tools">Tools</a>
		</li>
		<li class="navigation-menu-item">
			<a href="{% url 'exhibitions:detail' exhibition.slug %}#trainings">Trainings</a>
		</li>

		<li class="navigation-menu-item">
			<a href="{% url 'exhibitions:past' exhibition.slug %}">Past Trainings</a>
		</li>

		<li class="navigation-menu-item">
			<a href="{% url 'exhibitions:detail' exhibition.slug %}#facilitators">Facilitators</a>
		</li>
		{% for content_block in content_blocks %}
		{% if not forloop.first %}
		<li class="navigation-menu-item">
			<a href="{% url 'exhibitions:detail' exhibition.slug %}#{{ content_block.slug }}">{{ content_block.name }}</a>
		</li>
		{% endif %}
		{% endfor %}
	</ul>
</nav>

exhibitions/templates/exhibitions/past.html
{% extends "exhibitions/base.html" %}

{% block navigation %}
{% include 'exhibitions/navigation.html' %}
{% endblock navigation %}

{% block content %}

<!-- TRAININGS -->
<section class="section section-trainings section-past-trainings" id="past-trainings">
	<h2 class="section-header">PAST TRAININGS  <a href="#past-trainings"><i class="fa fa-chain fa-chain-big"></i></a></h2>
	{% include 'exhibitions/trainings.html' %}
</section>

{% endblock content %}

exhibitions/templates/exhibitions/tools.html
{% load image_tags %}

<section class="section section-tools" id="tools">
	<h2 class="section-header">TOOLS <a href="#tools"><i class="fa fa-chain fa-chain-big"></i></a></h2>
	<div class="section-content">
		<div class="tools-row">
		{% for tool in tools %}
			<div class="tool" id="{{ tool.slug }}">
				<img 
					class="tool-image" 
					src="{{ tool.image.url }}" 
					srcset="{{ tool.image | srcset }}"
					alt="{{ tool.name }}" 
					loading="lazy"
				/>
				<h3 class="tool-name">{{ tool.name }} <a href="#{{ tool.slug }}"><i class="fa fa-chain"></i></a></h3>

				<span class="tool-meta">Tool Type: </span>{{ tool.get_type_display }}
				<br />

				<span class="tool-meta">Made by: </span>{{ tool.made_by }}
				<br />

				<span class="tool-meta">Info: </span>{{ tool.info }}
				<br />

				<span class="tool-meta">Training:</span>
				{% if tool.training_set.all %}
				{% for training in tool.training_set.all %}
						<a class="tool-training" href="#{{ training.slug }}">{{ training.name }}</a>
				{% endfor %}
				{% else %}
				None at this time
				{% endif %}
				<br />

				{% if tool.facilitator_set.all %}
				{% for facilitator in tool.facilitator_set.all %}
				<span class="tool-meta">Facilitator: </span>
				<a class="tool-facilitator" href="#{{ facilitator.slug }}">{{ facilitator.name }}</a>
				{% endfor %}
				{% endif %}
			</div>
		{% if forloop.counter|divisibleby:"3" %}
		</div>
		<div class="tools-row">
		{% endif %}
		{% endfor %}
	</div>
</section>

exhibitions/templates/exhibitions/trainings.html
<div class="section-content">
	{% for training in trainings %}
	<div class="training" id="{{ training.slug }}">
		<h3 class="training-time">{{ training.name }} <a href="#{{ training.slug }}"><i class="fa fa-chain"></i></a></h3>
		<span class="training-name">{{ training.date|date:"l, F j, g:iA" }}</span>
		<br />
		<span class="training-facilitator">{{ training.facilitators.first.name }}</span>
		<br />
		<div class="training-description">{{ training.description|safe }}</div>
		<a class="training-rsvp" href="{{ training.link }}" target="_blank">RSVP</a>
	</div>
	{% endfor %}
	<div class="training" style="text-align:center;">
		<a href="{{ site_url }}/past">See past trainings</a>
	</div>
</div>