base/urls.py
from django.conf.urls import url
from . import views
from six import python_2_unicode_compatible


app_name = 'base'
urlpatterns = [
	url(r'^readings/(?P<slug>[0-9A-Za-z\-_]+)', views.TagDetailView.as_view(), name='tag-detail'),
	url(r'^practice/(?P<slug>[0-9A-Za-z\-_]+)', views.PracticeDetailView.as_view(), name='practice-detail'),
  url(r'^mailing-list/join', views.MailingListJoinView.as_view(), name='mailing-list-join'),
  url(r'^pastevents', views.PastView.as_view(), name='past-events'),
  url(r'^$', views.IndexView.as_view(), name='index'),
]

base/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db.models import *
from django.utils.html import format_html
from tinymce.models import HTMLField
from taggit.managers import TaggableManager
from six import python_2_unicode_compatible
from django.db.models.signals import post_save, post_delete
from django.core.cache import cache
from django.dispatch import receiver


@python_2_unicode_compatible
class Base(Model):
    class Meta:
        abstract = True

    name = CharField(max_length=200)
    slug = CharField(max_length=200)
    created = DateTimeField(auto_now_add=True, editable=False)
    updated = DateTimeField(auto_now=True, editable=False)

    @property
    def url(self):
        return "%s/%s" % (settings.SITE_URL, self.slug)

    def __str__(self):
        return self.name


class OrderedResource(Model):
    class Meta:
        abstract = True

    order = PositiveSmallIntegerField(default=0)
    is_primary = BooleanField(default=False)
    created = DateTimeField(auto_now_add=True, editable=False)
    updated = DateTimeField(auto_now=True, editable=False)


class BaseImage(OrderedResource):
    class Meta:
        abstract = True

    image = ImageField(upload_to='images', verbose_name='Image')

    @property
    def image_tag(self):
        return format_html('<img src="%s%s" height="100" />' % (settings.MEDIA_URL, self.image))


class BasePdf(OrderedResource):
    class Meta:
        abstract = True

    name = CharField(max_length=200)
    pdf = FileField(upload_to='pdfs', blank=True, null=True)


class ContentBlock(Base):
    class Meta:
        ordering = ['position', 'name']

    content = HTMLField()
    position = PositiveSmallIntegerField(null=True)
    is_on_main_site = BooleanField(default=True)


class Tool(Base):
    class Meta:
        ordering = ['type', 'name']

    TOOL_CHOICES = (
        ('use', 'In Use'),
        ('view', 'On View'),
        ('future', 'Future Tool'),
    )
    made_by = CharField(max_length=200, null=True)
    info = CharField(max_length=255, null=True)
    image = ImageField(null=True, upload_to='tools')
    pdf = FileField(upload_to='texts', blank=True, null=True)
    type = CharField(
        max_length=8,
        choices=TOOL_CHOICES,
        default='use',
    )


class Facilitator(Base):
    class Meta:
        ordering = ['name']

    tools = ManyToManyField(Tool, blank=True)
    description = HTMLField()


class Training(Base):
    class Meta:
        ordering = ['date', 'name']
        verbose_name = 'Event'

    date = DateTimeField()
    contributors = ManyToManyField('Contributor', blank=True)
    facilitators = ManyToManyField(Facilitator, blank=True)
    tools = ManyToManyField(Tool, blank=True)
    description = HTMLField(null=True, blank=True)
    link = URLField()

    @property
    def leaders(self):
        if (self.contributors):
            return self.contributors
        else:
            return self.facilitators

class Reading(Base):
    class Meta:
        ordering = ['name']

    pdf = FileField(upload_to='texts', blank=True, null=True)
    tags = TaggableManager()

    @property
    def sorted_tags(self):
        return self.tags.order_by('name')


class Contributor(Base):
    class Meta:
        ordering = ['name']

    bio = HTMLField(blank=True, null=True)


class Practice(Base):
    class Meta:
        ordering = ['name']

    contributors = ManyToManyField(Contributor)
    description = HTMLField(null=True, blank=True)
    tools = ManyToManyField(Tool, blank=True)
    trainings = ManyToManyField(Training, blank=True)
    readings = ManyToManyField(Reading, blank=True)
    link = URLField(blank=True, null=True)
    tags = TaggableManager()

    @property
    def primary_image(self):
        qs = self.practiceimage_set.filter(is_primary=1)
        if len(qs) > 0:
            return qs[0]
        return None

    @property
    def primary_pdf(self):
        qs = self.practicepdf_set.filter(is_primary=1)
        if len(qs) > 0:
            return qs[0]
        return None

    @property
    def sorted_tags(self):
        return self.tags.filter(reading__name__isnull=False).distinct().order_by('name')


class PracticeImage(BaseImage):
    practice = ForeignKey(Practice, on_delete = CASCADE)


class  PracticePdf(BasePdf):
    practice = ForeignKey(Practice, on_delete = CASCADE)

@receiver([post_save, post_delete])
def clear_the_cache(**kwargs):
    cache.clear() 

base/views.py
from datetime import datetime, timedelta, time
from django.conf import settings
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from taggit.models import Tag
from .models import (
    Contributor,
    Practice,
    Reading,
    Training,
    ContentBlock
)
from six import python_2_unicode_compatible

class IndexView(generic.TemplateView):
    template_name = 'base/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)

        today = datetime.now().date()

        context['contributors'] = Contributor.objects.all()
        context['practices'] = Practice.objects.all()
        context['trainings'] = Training.objects.filter(date__gte=today)
        context['content_blocks'] = ContentBlock.objects.filter(is_on_main_site=True)

        if 'slug' in self.kwargs:
            context['slug'] = self.kwargs['slug']

        return context


class TagDetailView(generic.TemplateView):
    template_name = 'base/tag-detail.html'
    model = Tag

    def get_context_data(self, **kwargs):
        context = super(TagDetailView, self).get_context_data(**kwargs)

        tag = get_object_or_404(Tag, slug=self.kwargs['slug'])

        readingsQuerySet = Reading.objects.filter(tags__slug__in=[tag.slug]).distinct()
        practiceQuerySet = Practice.objects.filter(readings__in=readingsQuerySet).distinct()
        contributorQuerySet = Contributor.objects.filter(practice__in=practiceQuerySet).distinct()

        context['readings'] = readingsQuerySet
        context['practices'] = practiceQuerySet
        context['contributors'] = contributorQuerySet
        context['content_blocks'] = ContentBlock.objects.filter(is_on_main_site=True)
        context['tag'] = tag
        context['all_tags'] = Tag.objects.filter(reading__name__isnull=False).distinct().order_by('name')

        return context


class PracticeDetailView(generic.DetailView):
    template_name = 'base/practice-detail.html'
    model = Practice

    def get_context_data(self, **kwargs):
        context = super(PracticeDetailView, self).get_context_data(**kwargs)

        today = datetime.now().date()

        context['contributors'] = Contributor.objects.all()
        context['practices'] = Practice.objects.all()
        context['trainings'] = Training.objects.filter(date__gte=today)
        context['content_blocks'] = ContentBlock.objects.filter(is_on_main_site=True)

        if 'slug' in self.kwargs:
            context['slug'] = self.kwargs['slug']

        return context


class PastView(generic.TemplateView):
    template_name = 'base/past.html'

    def get_context_data(self, **kwargs):
        context = super(PastView, self).get_context_data(**kwargs)

        today = datetime.now().date()

        context['trainings'] = Training.objects.filter(date__lte=today).order_by('-date')
        context['content_blocks'] = ContentBlock.objects.filter(is_on_main_site=True)

        return context


class MailingListJoinView(generic.TemplateView):
    template_name = 'base/mailing-list-join.html'

    def get_context_data(self, **kwargs):
        context = super(MailingListJoinView, self).get_context_data(**kwargs)
        context['content_blocks'] = ContentBlock.objects.filter(is_on_main_site=True)

        return context


def handle_page_not_found(request, exception):
    return redirect('base:index')

base/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Wound</title>
	<meta name="description" content="" />
	<meta name="keywords" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'base/css/style.css' %}" />
</head>
<body>
    {% block navigation %}
    {% endblock navigation %}
    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>
    <script type="text/javascript" src="{% static 'base/js/min/velocity.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'base/js/min/velocity.ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'base/js/site.js' %}"></script>
</body>
</html>

base/templates/base/artists.html
<section class="section section-artists" id="artists">
  <h2 class="section-header section-header--artists">ARTISTS <a href="#artists"><i class="fa fa-chain fa-chain-big"></i></a></h2>
  <div class="section-content">
    <div class="section__row">
    {% for contributor in contributors %}
      {% if contributor.bio %}
      <div class="item item--text" id="{{ contributor.slug }}">
        <span class="item__name item__name--contributor">{{contributor.name}}</span>
        <a href="{% url 'base:index' %}#{{ contributor.slug }}">
          <i class="fa fa-chain"></i>
        </a>
        <div class="item__description">{{ contributor.bio|safe }}</div>
        {% if contributor.bio|length > 300 %}
        <a href="#" class="item__toggle">read more</a>
        {% endif %}
      </div>
      {% if forloop.counter|divisibleby:"2" %}
    </div>
    <div class="section__row">
      {% endif %}
    {% endif %}
    {% endfor %}
  </div>
</section>

base/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Study</title>
	<meta name="description" content="" />
	<meta name="keywords" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'base/css/style.css' %}" />
</head>
<body>
    {% block navigation %}
    {% endblock navigation %}
    <div class="content">
        {% block content %}
        {% endblock content %}
    </div>
    <script type="text/javascript" src="{% static 'base/js/min/velocity.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'base/js/min/velocity.ui.min.js' %}"></script>
    <script src="https://player.vimeo.com/api/player.js"></script>
    <script>
        var videoPlayer = new Vimeo.Player('featured');
    </script>
    <script type="text/javascript" src="{% static 'base/js/site.js' %}"></script>
</body>
</html>

base/templates/base/content-blocks.html
{% for content_block in content_blocks %}
	{% if not forloop.first %}
	<!-- {{ content_block.name|upper }} -->
	<section class="section section-{{ content_block.slug }}" id="{{ content_block.slug }}">
		<h2 class="section-header">{{ content_block.name|upper }}  <a href="#{{ content_block.slug }}"><i class="fa fa-chain fa-chain-big"></i></a></h2>
		<div class="section-content">{{ content_block.content|safe }}</div>
	</section>
	{% endif %}
{% endfor %}

base/templates/base/detail.html
<h1>{{ tool.caption }}</h1>

base/templates/base/index.html
{% extends "base/base.html" %}

{% block navigation %}
{% include 'base/navigation.html' %}
{% endblock navigation %}

{% block content %}

{% include 'base/video.html' %}

{% include 'base/intro.html' %}

{% include 'base/practices.html' %}

{% include 'base/artists.html' %}

{% include 'base/resources.html' %}

<section class="section section--trainings" id="events">
  <h2 class="section-header">EVENTS  <a href="#events"><i class="fa fa-chain fa-chain-big"></i></a></h2>
  {% include 'base/trainings.html' %}
  <div class="training" style="text-align:center;">
    <a href="{% url 'base:past-events' %}">See past events</a>
  </div>
</section>

{% include 'base/content-blocks.html' %}

{% endblock content %}

base/templates/base/intro.html
{% load static %}

<header id="header">
	<!-- INTRO -->
	<section class="section section-intro section-{{ content_blocks.first.slug }}" id="{{ content_blocks.first.slug }}">
		<div class="section-content">
			<h1 class="header-text">STUDY COLLABORATION</h1>
			{{ content_blocks.first.content|safe }}
		</div>
	</section>
</header>

base/templates/base/mailing-list-join.html
{% extends "base/base.html" %}

{% block navigation %}
{% include 'base/navigation.html' %}
{% endblock navigation %}

{% block content %}

<section class="section section-mailing-list" id="past-trainings">
  <h2 class="section-header">JOIN THE MAILING LIST  <a href="{% url 'base:mailing-list-join' %}"><i class="fa fa-chain fa-chain-big"></i></a></h2>
  <div class="section-content">
    <form action="">
      <label for="email">Email Address</label>
      <input name="" type="text" id="email"/>

      <label for="first_name">First Name</label>
      <input name="" type="text" id="first_name"/>

      <label for="last_name">Last Name</label>
      <input name="" type="text" id="last_name"/>

      <p>Email me about</p>
      <input type="checkbox" name="" id="a1" value="New Collaborative Methods"/>
      <label for="a1">New Collaborative Methods</label>
      <input type="checkbox" name="" id="a2" value="Upcoming Events and Trainings"/>
      <label for="a2">Upcoming Events and Trainings</label>
      <input type="checkbox" name="" id="a3" value="Jobs">
      <label for="a3">Jobs</label>

      <label for="comments">Comments?</label>
      <input name="" type="text" id="comments"/>

      <input class="button" type="submit" value="Submit">
    </form>
  </div>
</section>

{% endblock content %}

base/templates/base/navigation.html
<nav class="navigation">
	<div class="navicon">&#9776;</div>
	<ul class="navigation-menu">
		<li class="navigation-menu-item">
			<a href="{% url 'base:index' %}#methods">Methods</a>
		</li>
		<li class="navigation-menu-item">
			<a href="{% url 'base:index' %}#artists">Artists</a>
		</li>
		<li class="navigation-menu-item">
			<a href="{% url 'base:index' %}#events">Events</a>
		</li>
		{% for content_block in content_blocks %}
		{% if not forloop.first %}
		<li class="navigation-menu-item">
			<a href="{% url 'base:index' %}#{{ content_block.slug }}">{{ content_block.name }}</a>
		</li>
		{% endif %}
		{% endfor %}
	</ul>
</nav>

base/templates/base/past.html
{% extends "base/base.html" %}

{% block navigation %}
{% include 'base/navigation.html' %}
{% endblock navigation %}

{% block content %}

<!-- TRAININGS -->
<section class="section section-trainings section-past-trainings" id="past-trainings">
  <h2 class="section-header">PAST EVENTS  <a href="{% url 'base:past-events' %}"><i class="fa fa-chain fa-chain-big"></i></a></h2>
  {% include 'base/trainings.html' %}
</section>

{% endblock content %}

base/templates/base/practice-detail.html
{% extends "base/base.html" %}

{% load static %}
{% load image_tags %}

{% block navigation %}
{% include 'base/navigation.html' %}
{% endblock navigation %}

{% block content %}
<section class="section section--detail section--{{practice.slug}}">
	<h2 class="section-header">
		{{practice.name|upper}}
		<a href="{% url 'base:practice-detail' slug=practice.slug %}">
			<i class="fa fa-chain fa-chain-big"></i>
		</a>
	</h2>
	<div class="section-content">
		<div class="item item--detail">
			{% if practice.primary_image %}
			<img 
				class="item__primary-image" 
				src="{% get_media_prefix %}{{ practice.primary_image.image }}" 
				srcset="{{ practice.primary_image.image | srcset }}"
				alt="{{ project.name }}" 
				loading="lazy"
			/>
			{% endif %}

			{% if practice.sorted_tags %}
			<div class="item__meta">
				<p class="item__tags">
				{% for tag in practice.sorted_tags.all %}
					(<a class="tag" href="{% url 'base:tag-detail' tag.slug %}">{{ tag.name }}</a>)
				{% endfor %}
				</p>
			</div>
			{% endif %}

			{% if practice.contributors.all %}
			<div class="item__meta">
				<span class="item__key">Contributed By: </span>
				<span class="item__value">
				{% for contributor in practice.contributors.all %}
				<a href="{% url 'base:index' %}#{{ contributor.slug }}">{{ contributor.name }}</a>{% if not forloop.last %}, {% endif %}
				{% endfor %}
				</span>
			</div>
			{% endif %}

			{% if practice.description %}
			<div class="item__meta">
				<span class="item__value">{{ practice.description|safe }}</span>
			</div>
			{% endif %}

			{% if practice.primary_pdf %}
			<div class="item__meta">
				<span class="item__key">PDF: </span>
				<span class="item__value">
					{% for pdf in practice.practicepdf_set.all %}
  				<a class="item-pdf" target="_blank" href="{{ pdf.pdf.url }}">
  					{{ pdf.name }}
  				</a>
  				{% endfor %}
				</span>
			</div>
			{% endif %}

			{% if practice.link %}
			<div class="item__meta">
				<span class="item__key">Website: </span>
				<span class="item__value">
					<a href="{{ practice.link }}" target="_blank">
						{{ practice.link }}
					</a>
				</span>
			</div>
			{% endif %}

			{% if practice.readings.length > 0 %}
			<div class="item__meta">
				<span class="item__key">Additional Readings: </span>
				<span class="item__value">
				{% for reading in practice.readings.all %}
					<a class="practice-reading" target="_blank" href="{% get_media_prefix %}{{ reading.pdf }}">
						{{ reading.name }}
					</a>
				{% endfor %}
				</span>
			</div>
			{% endif %}

			{% if practice.practiceimage_set.all %}
			<div class="item__gallery gallery">
			{% for item in practice.practiceimage_set.all %}
			{% if not item.is_primary %}
				<div class="gallery__item">
					<img 
						class="gallery__image" 
						src="{% get_media_prefix %}{{ item.image }}" 
						srcset="{{ item.image | srcset }}"
						alt="{{ practice.name }}" 
						loading="lazy"
					/>
				</div>
			{% endif %}
			{% endfor %}
			</div>
			{% endif %}

			{% for contributor in practice.contributors.all %}
			{% if contributor.bio %}
			<div class="item__meta">
				<span class="item__key">About {{ contributor }}: </span>
				<span class="item__value">{{ contributor.bio|safe }}</span>
			</div>
			{% endif %}
			{% endfor %}
		</div>
	</div>
</section>
{% endblock content %}

base/templates/base/practices.html
{% load static %}
{% load image_tags %}

<section class="section section-practices" id="methods">
	<h2 class="section-header">COLLABORATIVE METHODS <a href="#metods"><i class="fa fa-chain fa-chain-big"></i></a></h2>
	<div class="section-content">
		<div class="section__row">
		{% for practice in practices %}
			<div class="item">
				<a href="{% url 'base:practice-detail' slug=practice.slug %}">
					{% if practice.primary_image %}
					<img 
						class="practice__primary-image" 
						src="{% get_media_prefix %}{{ practice.primary_image.image }}" 
						srcset="{{ practice.primary_image.image | srcset }}"
						sizes="(min-width: 1140px) 513px, 100vw"
						alt="{{ project.name }}" 
						loading="lazy"
					/>
					{% else %}
					<div class="practice__primary-image practice__primary-image--placeholder"></div>
					{% endif %}
				</a>

				<h3 class="item__name">
					<a href="{% url 'base:practice-detail' slug=practice.slug %}">
						{{ practice.name }}
					</a>
					<a href="{% url 'base:practice-detail' slug=practice.slug %}">
						<i class="fa fa-chain"></i>
					</a>
				</h3>

				<div class="item__meta">
					<span class="item__key">Contributed By: </span>
					<span class="item__value">
					{% for contributor in practice.contributors.all %}
						<span class="item__contributor"><a href="#{{contributor.slug}}">{{contributor.name}}</a>{% if forloop.last %}{% else %}, {% endif %}<span>
					{% endfor %}
					</span>
				</div>

				{% if practice.sorted_tags.all %}
				<div class="item__meta">
					<span class="item__key">Tags: </span>
					<span class="item__value">
					{% for tag in practice.sorted_tags.all %}
						(<a class="tag" href="{% url 'base:tag-detail' tag.slug %}">{{ tag.name }}</a>){% if forloop.last %}{% else %}, {% endif %}
					{% endfor %}
					</span>
				</div>
				{% endif %}
			</div>
		{% if forloop.counter|divisibleby:"2" %}
		</div>
		<div class="section__row">
		{% endif %}
		{% endfor %}
	</div>
</section>

base/templates/base/tag-detail.html
{% extends "base/base.html" %}

{% load static %}

{% block navigation %}
{% include 'base/navigation.html' %}
{% endblock navigation %}

{% block content %}
<section class="section section--detail section--tag section--{{tag.slug}}">
	<h2 class="section-header">
		({{tag.name|upper}})
		<a href="{% url 'base:tag-detail' slug=tag.slug %}">
			<i class="fa fa-chain fa-chain-big"></i>
		</a>
	</h2>
	<div class="section-content">
		<div class="item--detail">
			<div class="item__meta">
				<span class="item__key">Contributed By: </span>
				<span class="item__value">
					{% for contributor in contributors %}
					<span class="item__contributor">
						<a href="{% url 'base:index' %}#{{ contributor.slug }}">{{ contributor.name }}</a>{% if forloop.last %}{% else %}, {% endif %}
					</span>
					{% endfor %}
				</span>
			</div>

			<div class="item__meta">
				<span class="item__key">Associated Methods: </span>
				<span class="item__value">
					{% for practice in practices %}
					<span class="item__contributor">
						<a href="{% url 'base:practice-detail' slug=practice.slug %}">{{ practice.name }}</a>{% if forloop.last %}{% else %}, {% endif %}
					</span>
					{% endfor %}
				</span>
			</div>

			<ul class="item__list">
				<li class="list__item list__item--header">
					<span class="reading__name">PDF</span>
					<span class="reading__tags">TAGS</span>
				</li>
			{% for reading in readings %}
				<li class="list__item">
					<span class="reading__name">
						<span class="name__label">PDF: </span>
						<a target="_blank" href="{% get_media_prefix %}{{reading.pdf}}">{{ reading.name }}</a>
					</span>
					<span class="reading__tags">
					<span class="tags__label">TAGGED: </span>
					{% for tag in reading.sorted_tags.all %}
						(<a class="reading__tag" href="{% url 'base:tag-detail' tag.slug %}">{{ tag.name }}</a>)
					{% endfor %}
					</span>
				</li>
			{% endfor %}
			</ul>
		</div>
	</div>
</section>
<section class="section section--detail section--all-tags">
	<h2 class="section-header">
		TAGS
	</h2>
	<div class="section-content">
		<div class="item--detail">
		{% for tag in all_tags %}
			<span class="all-tags__item">
				(<a class="reading__tag" href="{% url 'base:tag-detail' tag.slug %}">{{ tag.name }}</a>)
			</span>
		{% endfor %}
		</div>
	</div>
</section>
{% endblock content %}

base/templates/base/trainings.html
<div class="section-content">
  {% for training in trainings %}
  <div class="training" id="{{ training.slug }}">
    <h3 class="training-time">{{ training.name }} <a href="#{{ training.slug }}"><i class="fa fa-chain"></i></a></h3>
    <span class="training-name">{{ training.date|date:"l, F j, g:iA" }}</span>
    <br />
    <span class="training-facilitator">{{ training.leaders.first.name }}</span>
    <br />
    <div class="training-description">{{ training.description|safe }}</div>
    <a class="training-rsvp" href="{{ training.link }}" target="_blank">RSVP</a>
  </div>
  {% empty %}
  <div class="training--empty">
    <span>No events scheduled at the moment</span>
  </div>
  {% endfor %}
</div>

base/templates/base/video.html
{% load static %}

<section class="section section--video">
  <div class='video'>
    <div
      data-vimeo-url="https://vimeo.com/323043636/3162d93dcc"
      data-vimeo-autoplay="true"
      data-vimeo-loop="true"
      data-vimeo-title="false"
      data-vimeo-byline="false"
      id="featured">
    </div>
  </div>
</section>

base/templates/index.html
{% extends "base.html" %}

{% block navigation %}
{% include 'navigation.html' %}
{% endblock navigation %}

{% block content %}

{% include 'intro.html' %}

<!-- TOOLS -->
{% include 'tools.html' %}

<!-- TRAININGS -->
<section class="section section-trainings" id="trainings">
	<h2 class="section-header">TRAININGS  <a href="#trainings"><i class="fa fa-chain fa-chain-big"></i></a></h2>
	{% include 'trainings.html' %}
</section>

<!-- FACILITATORS -->
{% include 'facilitators.html' %}

{% include 'content-blocks.html' %}

{% endblock content %}